layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-paginate-v2
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_anime"
    values:
      layout: "anime"

pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

collections: 
  anime:
    output: true
    permalink: "/anime/:path/"

  people:
    output: false
