name: 'Push to GitHub'
description: 'Pushes code to Github'
inputs:
  branch:
    description: Branch of the repository to push to
    required: true
  repository:
    description: Target repository
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        BRANCH: ${{inputs.branch}}
        REPOSITORY: ${{inputs.repository}}
