name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  buildNdeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ${{ github.workspace }}/vendor/bundle
          key: gem_dependencies
      - name: Install/Upgrade gems
        run: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-${{ env.workspace }}}
      - name: Build website
        run: bundle exec jekyll build
      - name: Copy built files to the right directory
        run: |
          TEMP_DIR=$(mktemp -d)
          mv -r ./_site/* ${TEMP_DIR}
          git checkout gh-pages
          mv -r ${TEMP_DIR}/* .
      - name: Deploy
        uses: ./github/actions/pushToGithub/action.sh
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          username: ${{ github.repository_owner }}
          branch: gh-pages
          repository: ${{ github.repository }}.git
