name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  buildNdeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source
          ref: 'master'
      - name: Checkout built branch
        uses: actions/checkout@v2
        with:
          path: built
          ref: 'gh-pages'
      - name: Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ${{ github.workspace }}/source/vendor/bundle
          key: gem_dependencies
      - name: Install/Upgrade gems
        run: |
          cd ${{ github.workspace }}/source
          bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-${{ github.workspace }}/source/vendor/bundle}
          cd -
      - name: Build website
        run: |
          cd ${{ github.workspace }}/source
          bundle exec jekyll build
          cd -
      - name: Copy built files to the built directoryy
        run: mv ./source/_site/* ./built/
      - name: Deploy
        uses: ./github/actions/pushToGithub/action.sh
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          username: ${{ github.repository_owner }}
          branch: gh-pages
          repository: ${{ github.repository }}.git
